# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ cd_userprofile ]
    paths: 
      - 'apis/userprofile/**' 
      - '.github/workflows/nodejs.yml'   
  pull_request:
    branches: [ master ]
    paths: 
      - 'apis/userprofile/**' 
      - '.github/workflows/nodejs.yml' 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: npm ci
      working-directory: ./apis/userprofile
      
    - name: npm run build
      run: npm run build --if-present
      working-directory: ./apis/userprofile
  
    - name: npm test
      run: npm test
      working-directory: ./apis/userprofile

  docker_build_and_push:
    if: github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: openhack2b446dk2acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: test docker version
      working-directory: ./apis/userprofile
      run: |
        ls
        pwd
        docker version
    
    - name: docker build push
      working-directory: ./apis/userprofile
      run: |
        docker build -t openhack2b446dk2acr.azurecr.io/devopsoh/api-userprofile:${{ github.sha }} .
        docker push openhack2b446dk2acr.azurecr.io/devopsoh/api-userprofile:${{ github.sha }}

  cd_to_webapp:
    if: github.event_name == 'push'
    needs: [docker_build_and_push]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack2b446dk2userprofile'
        slot-name: 'staging'
        images: 'openhack2b446dk2acr.azurecr.io/devopsoh/api-userprofile:${{ github.sha }}'
    
